// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "mmtty4mac",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "WaveFile", targets: ["WaveFile"]),
        .library(name: "ModemKit", targets: ["ModemKit"]),
        .library(name: "RTTYModem", targets: ["RTTYModem"]),
        .executable(name: "rtty-tool", targets: ["rtty-tool"]),
        .executable(name: "MMTTY4MacApp", targets: ["MMTTY4MacApp"]),
    ],
    targets: [
        .target(name: "WaveFile"),
        .testTarget(name: "WaveFileTests", dependencies: ["WaveFile"]),
        .target(
            name: "MMTTYCore",
            path: "Sources/MMTTYCore",
            cxxSettings: [
                .headerSearchPath("mmtty"),
                .headerSearchPath("compat"),
                .unsafeFlags(["-Wno-deprecated-declarations", "-Wno-writable-strings",
                              "-Wno-parentheses", "-Wno-dangling-else", "-Wno-unused-variable",
                              "-Wno-nontrivial-memcall"]),
            ]
        ),
        .testTarget(name: "MMTTYCoreTests", dependencies: ["MMTTYCore", "RTTYSignalKit", "WaveFile"],
                    resources: [.copy("Fixtures")]),
        .target(name: "ModemKit"),
        .testTarget(name: "ModemKitTests", dependencies: ["ModemKit"]),
        .target(name: "RTTYModem", dependencies: ["MMTTYCore", "ModemKit"]),
        .testTarget(name: "RTTYModemTests", dependencies: ["RTTYModem", "ModemKit", "RTTYSignalKit"]),
        .executableTarget(name: "rtty-tool", dependencies: ["RTTYModem", "ModemKit", "WaveFile", "RTTYSignalKit",
                                                          "Engine", "AudioIO", "Keying", "RigControl",
                                                          "MacroEngine", "Settings", "AppCore", "APIServer", "QSOLog"]),
        .target(name: "XMLRPC"),
        .testTarget(name: "XMLRPCTests", dependencies: ["XMLRPC"]),
        .target(name: "RigControl", dependencies: ["XMLRPC", "CSerial"]),
        .testTarget(name: "RigControlTests", dependencies: ["RigControl", "XMLRPC", "CSerial"]),
        .target(name: "CSerial"),
        .target(name: "Keying", dependencies: ["CSerial", "RigControl"]),
        .target(name: "TestSupport", dependencies: ["Keying", "AudioIO"]),
        .target(name: "Engine", dependencies: ["ModemKit", "AudioIO", "Keying", "RigControl", "MacroEngine"]),
        .testTarget(name: "EngineTests", dependencies: ["Engine", "RTTYModem", "RTTYSignalKit", "TestSupport",
                                                        "AudioIO", "Keying", "ModemKit", "RigControl", "MacroEngine"]),
        .testTarget(name: "KeyingTests", dependencies: ["Keying", "RigControl", "TestSupport"]),
        .target(name: "CRingBuffer"),
        .target(name: "AudioIO", dependencies: ["CRingBuffer"]),
        .testTarget(name: "AudioIOTests", dependencies: ["AudioIO"]),
        .target(name: "QSOLog"),
        .testTarget(name: "QSOLogTests", dependencies: ["QSOLog"]),
        .target(name: "MacroEngine"),
        .testTarget(name: "MacroEngineTests", dependencies: ["MacroEngine"]),
        .target(name: "Settings", dependencies: ["Engine", "AudioIO", "Keying", "ModemKit", "Localization"]),
        .testTarget(name: "SettingsTests", dependencies: ["Settings", "Engine", "AudioIO", "Keying", "ModemKit"]),
        .target(name: "AppCore", dependencies: ["Engine", "Settings", "QSOLog", "MacroEngine", "ModemKit", "RigControl", "DXCC", "Localization"]),
        .testTarget(name: "AppCoreTests", dependencies: ["DXCC", "AppCore", "Engine", "Settings", "QSOLog", "ModemKit", "RigControl",
                                                         "RTTYModem", "RTTYSignalKit", "TestSupport", "AudioIO", "Keying"]),
        .target(name: "APIServer", dependencies: ["DXCC", "AppCore", "Engine", "XMLRPC", "QSOLog", "ModemKit", "Settings", "RigControl", "MacroEngine"]),
        .testTarget(name: "APIServerTests", dependencies: ["APIServer", "AppCore", "Engine", "XMLRPC", "QSOLog", "ModemKit", "Settings",
                                                           "RigControl", "RTTYModem", "RTTYSignalKit", "TestSupport", "AudioIO", "Keying"]),
        .target(name: "AppUI", dependencies: ["DXCC", "AppCore", "APIServer", "Engine", "Settings", "QSOLog", "ModemKit",
                                               "AudioIO", "Keying", "RigControl", "RTTYModem", "WaveFile", "Localization", "Updates"]),
        .testTarget(name: "AppUITests", dependencies: ["AppUI", "AppCore", "Engine", "Settings", "ModemKit", "AudioIO",
                                                       "Keying", "RigControl", "RTTYModem", "RTTYSignalKit", "TestSupport", "WaveFile", "Updates"]),
        .target(name: "AppViews", dependencies: ["AppUI", "AppCore", "QSOLog", "Settings", "AudioIO", "Keying",
                                                  "ModemKit", "Engine", "RigControl", "RTTYModem", "Localization", "Updates"]),
        .executableTarget(name: "MMTTY4MacApp", dependencies: ["AppViews", "AppUI", "Localization", "Settings", "Updates"]),
        .target(name: "DXCC"),
        .target(name: "Localization"),
        .target(name: "Updates"),
        .testTarget(name: "UpdatesTests", dependencies: ["Updates"]),
        .testTarget(name: "LocalizationTests", dependencies: ["Localization"]),
        .testTarget(name: "DXCCTests", dependencies: ["DXCC"]),
        .target(name: "RTTYSignalKit"),
        .testTarget(name: "RTTYSignalKitTests", dependencies: ["RTTYSignalKit"]),
    ],
    cxxLanguageStandard: .cxx17
)
